#SPDX-License-Identifier: MIT-0
---
# handlers file for deploy_apache
- name: Restart Apache on Ubuntu
  service:
    name: apache2
    state: restarted

- name: Restart Apache on RedHat
  service:
    name: httpd
    state: restarted
